lirios-customization: Fix build break
This commit fixes the following build break:
ERROR: lirios-image-1.0-r0 do_rootfs: Postinstall scriptlets of ['lirios-customization'] have failed.
If the intention is to defer them to first boot,then please place them into pkg_postinst_ontarget_${PN} ().
Deferring to first boot via 'exit 1' is no longer supported.

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>